//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avalon.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avalon.Windows.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property type must be System.Double..
        /// </summary>
        internal static string Animator_PropertyMustBeDouble {
            get {
                return ResourceManager.GetString("Animator_PropertyMustBeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target must be an IAnimatable.
        /// </summary>
        internal static string Animator_TargetMustBeIAnimatable {
            get {
                return ResourceManager.GetString("Animator_TargetMustBeIAnimatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid enum value..
        /// </summary>
        internal static string ArgumentValidator_EnumValueIsDefined {
            get {
                return ResourceManager.GetString("ArgumentValidator_EnumValueIsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String cannot be null or empty..
        /// </summary>
        internal static string ArgumentValidator_NotNullOrEmptyString {
            get {
                return ResourceManager.GetString("ArgumentValidator_NotNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible type.
        /// </summary>
        internal static string ArgumentValidator_TypeIsAssignableFromType {
            get {
                return ResourceManager.GetString("ArgumentValidator_TypeIsAssignableFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of dependency property is incompatible with value..
        /// </summary>
        internal static string DependencyHelpers_IncompatibleDPType {
            get {
                return ResourceManager.GetString("DependencyHelpers_IncompatibleDPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized enum type..
        /// </summary>
        internal static string EnumHelper_InvalidObjectType {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource manager..
        /// </summary>
        internal static string EnumResourceTypeConverter_InvalidResourceManager {
            get {
                return ResourceManager.GetString("EnumResourceTypeConverter_InvalidResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add text children..
        /// </summary>
        internal static string IAddChild_NoText {
            get {
                return ResourceManager.GetString("IAddChild_NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add non-text children..
        /// </summary>
        internal static string IAddChild_TextOnly {
            get {
                return ResourceManager.GetString("IAddChild_TextOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateCalculator implementation must return a value..
        /// </summary>
        internal static string IAnimationCalculator_CreationFailed {
            get {
                return ResourceManager.GetString("IAnimationCalculator_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child must be a {0}KeyFrame..
        /// </summary>
        internal static string KeyFramesAnimationBase_ChildNotKeyFrame {
            get {
                return ResourceManager.GetString("KeyFramesAnimationBase_ChildNotKeyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid default value..
        /// </summary>
        internal static string LinearAnimationBase_InvalidDefaultValue {
            get {
                return ResourceManager.GetString("LinearAnimationBase_InvalidDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout cannot be negative..
        /// </summary>
        internal static string NotifyIcon_NoNegativeTimeout {
            get {
                return ResourceManager.GetString("NotifyIcon_NoNegativeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        internal static string TaskDialog_Buttons {
            get {
                return ResourceManager.GetString("TaskDialog_Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Links.
        /// </summary>
        internal static string TaskDialog_CommandLinks {
            get {
                return ResourceManager.GetString("TaskDialog_CommandLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string TaskDialog_Content {
            get {
                return ResourceManager.GetString("TaskDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded Information.
        /// </summary>
        internal static string TaskDialog_ExpandedInformation {
            get {
                return ResourceManager.GetString("TaskDialog_ExpandedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string TaskDialog_Footer {
            get {
                return ResourceManager.GetString("TaskDialog_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Instruction.
        /// </summary>
        internal static string TaskDialog_MainInstruction {
            get {
                return ResourceManager.GetString("TaskDialog_MainInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot show a TaskDialog that already has a parent..
        /// </summary>
        internal static string TaskDialog_NoParent {
            get {
                return ResourceManager.GetString("TaskDialog_NoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Buttons.
        /// </summary>
        internal static string TaskDialog_RadioButtons {
            get {
                return ResourceManager.GetString("TaskDialog_RadioButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Title.
        /// </summary>
        internal static string TaskDialog_WindowTitle {
            get {
                return ResourceManager.GetString("TaskDialog_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button must be a single value..
        /// </summary>
        internal static string TaskDialogButtonData_ButtonSingleValue {
            get {
                return ResourceManager.GetString("TaskDialogButtonData_ButtonSingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set properties on a standard button..
        /// </summary>
        internal static string TaskDialogButtonData_SetStandardButton {
            get {
                return ResourceManager.GetString("TaskDialogButtonData_SetStandardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string TaskDialogButtons_Cancel {
            get {
                return ResourceManager.GetString("TaskDialogButtons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_lose.
        /// </summary>
        internal static string TaskDialogButtons_Close {
            get {
                return ResourceManager.GetString("TaskDialogButtons_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string TaskDialogButtons_No {
            get {
                return ResourceManager.GetString("TaskDialogButtons_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        internal static string TaskDialogButtons_OK {
            get {
                return ResourceManager.GetString("TaskDialogButtons_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Retry.
        /// </summary>
        internal static string TaskDialogButtons_Retry {
            get {
                return ResourceManager.GetString("TaskDialogButtons_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string TaskDialogButtons_Yes {
            get {
                return ResourceManager.GetString("TaskDialogButtons_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type arguments need to be specified in the right order..
        /// </summary>
        internal static string TypeExtension_ArgumentsWrongOrder {
            get {
                return ResourceManager.GetString("TypeExtension_ArgumentsWrongOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type argument count in type..
        /// </summary>
        internal static string TypeExtension_InvalidTypeArgumentCount {
            get {
                return ResourceManager.GetString("TypeExtension_InvalidTypeArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type name..
        /// </summary>
        internal static string TypeExtension_InvalidTypeName {
            get {
                return ResourceManager.GetString("TypeExtension_InvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type argument count in type name..
        /// </summary>
        internal static string TypeExtension_InvalidTypeNameArgumentCount {
            get {
                return ResourceManager.GetString("TypeExtension_InvalidTypeNameArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve IXamlTypeResolver..
        /// </summary>
        internal static string TypeExtension_NoIXamlTypeResolver {
            get {
                return ResourceManager.GetString("TypeExtension_NoIXamlTypeResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify Type or TypeName..
        /// </summary>
        internal static string TypeExtension_TypeOrNameMissing {
            get {
                return ResourceManager.GetString("TypeExtension_TypeOrNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a Dispatcher..
        /// </summary>
        internal static string UIHelpers_NoDispatcher {
            get {
                return ResourceManager.GetString("UIHelpers_NoDispatcher", resourceCulture);
            }
        }
    }
}
